In [152]:
%pip install numpy
%pip install pandas
import numpy as np
import pandas as pd



Defaulting to user installation because normal site-packages is not writeable
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.
Defaulting to user installation because normal site-packages is not writeable
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


NUMPY

 Array Creation:

Create a NumPy array containing the numbers from 0 to 9. What is the shape and data type of this array?

In [153]:

s = np.arange(0,10)
print(s)
print(type(s))
print(s.shape)



[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
(10,)


 Array Shape:
Question: Create a 2D array with shape (3, 4) filled with random integers between 0 and 10. What is the shape of the resulting array?

In [154]:

a = np.random.randint(10,size=(3,4))
print(a)

[[7 6 2 0]
 [1 9 3 4]
 [3 8 5 2]]


3. Array Reshaping:
Question: Given the array arr = np.array([1, 2, 3, 4, 5, 6, 7, 8]), reshape it into a 2x4 matrix.

In [155]:
arr1 = np.array([1,2,3,4,5,6,7,8])
arr2 = arr1.reshape(2,4)
print(arr2)


[[1 2 3 4]
 [5 6 7 8]]


4. Array Indexing:
Question: From the following 2D array, extract the element in the 2nd row and 3rd column:


arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


In [156]:
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr3[1:2,2:3])

[[6]]


5. Slicing:
Question: Given a 1D array arr = np.arange(10), extract the elements from index 2 to index 6 (not inclusive).

In [157]:
arr4 = np.arange(10)
print(arr4[2:6])

[2 3 4 5]


6. Element-wise Operations:
Question: Create two NumPy arrays, arr1 = np.array([1, 2, 3]) and arr2 = np.array([4, 5, 6]). Perform element-wise addition, subtraction, and multiplication.

In [158]:
arr5 = np.array([1, 2, 3])
arr6 = np.array([4, 5, 6])
arr7 = arr5+arr6
print("addition",arr7)
arr8 = arr5 - arr6
print("subtraction",arr8)
arr9 = arr5 * arr6
print("multiplication",arr9)

addition [5 7 9]
subtraction [-3 -3 -3]
multiplication [ 4 10 18]


7. Broadcasting:
Question: Add a scalar value of 10 to each element of the array arr = np.array([1, 2, 3, 4, 5]) using broadcasting.


In [159]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr1 =arr+10
print(arr1)

[11 12 13 14 15 16 17 18]


8. Basic Statistical Operations:
Question: Create a NumPy array of 15 random integers between 0 and 50. Find the mean, median, and standard deviation of the array.


In [160]:
arr = np.random.randint(0,50,15)
print(arr)

[30 46 45  6 20 42 26 14 19 31 39 27 26 14 17]


9. Boolean Indexing:
Question: From the array arr = np.array([10, 20, 30, 40, 50]), extract all elements greater than 25.

In [161]:
arr = np.array([10, 20, 30, 40, 50])
arr1 = np.array(arr[arr > 25])
print(arr1)


[30 40 50]


10. Array Concatenation:
Question: Create two arrays arr1 = np.array([1, 2, 3]) and arr2 = np.array([4, 5, 6]). Concatenate them into a single array.


In [162]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.concatenate([arr1,arr2])
print(arr3)

[1 2 3 4 5 6]


PANDAS

1. DataFrame Creation:
Question: Create a Pandas DataFrame from the following dictionary:

Task 1: Display the DataFrame 
Task 2: Save it as “data.csv”


In [163]:
data = {'Name':['Alice','Bob','Charlie','David'],'Age':[25,30,35,40],'City':['New York','Los Angeles','Chicago','Houston']}
df = pd.DataFrame(data)
df.to_csv('data.csv')
df.head()

Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston

2. Reading a CSV File:
Question: Read a CSV file named data.csv into a Pandas DataFrame. Display the first 5 rows of the DataFrame.

In [164]:
df = pd.read_csv('data.csv',index_col=0 )
Data1 = df.head(5)
Data1.head()

Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston

3. Selecting a Column:
Question: From the loaded data, select and display the "Name" column.

In [165]:
df = pd.read_csv('data.csv', index_col=0)
Data1 = df['Name']
Data1.head()

0      Alice
1        Bob
2    Charlie
3      David
Name: Name, dtype: object

4. Filtering Rows:
Question: From the above DataFrame, filter and display only the rows where the "Age" is greater than 30.


In [166]:
df = pd.read_csv('data.csv', index_col=0)
df1=df[df['Age']>30]
df1.head()


Name  Age     City
2  Charlie   35  Chicago
3    David   40  Houston

5. Adding a New Column:
Question: Add a new column named "Salary" to the DataFrame with the values [50000, 60000, 70000, 80000].


In [167]:
df3= df.assign(Salary=[50000,60000,70000,80000])
df3.head()

Name  Age         City  Salary
0    Alice   25     New York   50000
1      Bob   30  Los Angeles   60000
2  Charlie   35      Chicago   70000
3    David   40      Houston   80000